length_in_x: 120
length_in_y: 120
position_x: 0.0
position_y: 0.0
resolution: 0.2
min_variance: 0.0001
max_variance: 10000.0
mahalanobis_distance_threshold: 2.5
multi_height_noise: 0.00002
time_tolerance: 0.5
enable_visibility_cleanup: false
sensor_processor/ignore_points_above: 0.8
fused_map_publishing_rate: 1.0
