input_sources:
  camera:
    type: pointcloud
    topic: /camera/depth/color/points
    queue_size: 5
    publish_on_update: false
    sensor_processor:
      type: structured_light
      cutoff_min_depth: 0.2
      cutoff_max_depth: 3.25
      normal_factor_a: 0.000611
      normal_factor_b: 0.003587
      normal_factor_c: 0.3515
      normal_factor_d: 0
      normal_factor_e: 1
      lateral_factor: 0.01576 # approx 1 deg
  lidar: # A name to identify the input source
    type: pointcloud # Supported types: pointcloud
    topic: /velodyne_points # your topic
    queue_size: 5
    publish_on_update: false # Whether to publish the elevation map after a callback from this source.
    sensor_processor:
      type: laser
      min_radius: 0.018
      beam_angle: 0.0006
      beam_constant: 0.0015

map_frame_id: "odom"
robot_base_frame_id: "/cassie/pelvis"
robot_pose_with_covariance_topic: "/cassie/pose"
robot_pose_cache_size: 2000
track_point_frame_id: "/cassie/pelvis"
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
