point_cloud_topic: "/spot_node/depth_image"
sensor_frame_id: "depth_image"
map_frame_id: "spot/odometry"
robot_base_frame_id: "left_color_camera"
robot_pose_with_covariance_topic: "/spot_node/left_color_camera_pose"
robot_pose_cache_size: 200
track_point_frame_id: "left_color_camera"
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
